package com.netease.Mutest.model;

import java.util.Date;

public class EntityTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.summary_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer summaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.type
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.case_num
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_test.case_passed
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer casePassed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.id
     *
     * @return the value of entity_test.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.id
     *
     * @param id the value for entity_test.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.create_time
     *
     * @return the value of entity_test.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.create_time
     *
     * @param createTime the value for entity_test.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.modify_time
     *
     * @return the value of entity_test.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.modify_time
     *
     * @param modifyTime the value for entity_test.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.summary_id
     *
     * @return the value of entity_test.summary_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.summary_id
     *
     * @param summaryId the value for entity_test.summary_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setSummaryId(Integer summaryId) {
        this.summaryId = summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.type
     *
     * @return the value of entity_test.type
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.type
     *
     * @param type the value for entity_test.type
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.case_num
     *
     * @return the value of entity_test.case_num
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.case_num
     *
     * @param caseNum the value for entity_test.case_num
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCaseNum(Integer caseNum) {
        this.caseNum = caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_test.case_passed
     *
     * @return the value of entity_test.case_passed
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCasePassed() {
        return casePassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_test.case_passed
     *
     * @param casePassed the value for entity_test.case_passed
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCasePassed(Integer casePassed) {
        this.casePassed = casePassed;
    }
}