package com.netease.Mutest.model;

import java.util.Date;

public class ErrorCases {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.case_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.error_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer errorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.error_type
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte errorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_cases.error_info
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String errorInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.id
     *
     * @return the value of error_cases.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.id
     *
     * @param id the value for error_cases.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.create_time
     *
     * @return the value of error_cases.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.create_time
     *
     * @param createTime the value for error_cases.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.modify_time
     *
     * @return the value of error_cases.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.modify_time
     *
     * @param modifyTime the value for error_cases.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.case_id
     *
     * @return the value of error_cases.case_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.case_id
     *
     * @param caseId the value for error_cases.case_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.error_id
     *
     * @return the value of error_cases.error_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getErrorId() {
        return errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.error_id
     *
     * @param errorId the value for error_cases.error_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setErrorId(Integer errorId) {
        this.errorId = errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.error_type
     *
     * @return the value of error_cases.error_type
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.error_type
     *
     * @param errorType the value for error_cases.error_type
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setErrorType(Byte errorType) {
        this.errorType = errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_cases.error_info
     *
     * @return the value of error_cases.error_info
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_cases.error_info
     *
     * @param errorInfo the value for error_cases.error_info
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo == null ? null : errorInfo.trim();
    }
}