package com.netease.Mutest.model;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_name
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.is_valid
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.operator
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.environment
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer environment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_time
     *
     * @return the value of report.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_time
     *
     * @param createTime the value for report.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.modify_time
     *
     * @return the value of report.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.modify_time
     *
     * @param modifyTime the value for report.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_name
     *
     * @return the value of report.report_name
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_name
     *
     * @param reportName the value for report.report_name
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.is_valid
     *
     * @return the value of report.is_valid
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.is_valid
     *
     * @param isValid the value for report.is_valid
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.operator
     *
     * @return the value of report.operator
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.operator
     *
     * @param operator the value for report.operator
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.environment
     *
     * @return the value of report.environment
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.environment
     *
     * @param environment the value for report.environment
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setEnvironment(Integer environment) {
        this.environment = environment;
    }
}