package com.netease.Mutest.model;

import java.util.Date;

public class Summary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.report_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.is_contextual
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte isContextual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.case_num
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary.case_passed
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer casePassed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.id
     *
     * @return the value of summary.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.id
     *
     * @param id the value for summary.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.create_time
     *
     * @return the value of summary.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.create_time
     *
     * @param createTime the value for summary.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.modify_time
     *
     * @return the value of summary.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.modify_time
     *
     * @param modifyTime the value for summary.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.report_id
     *
     * @return the value of summary.report_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.report_id
     *
     * @param reportId the value for summary.report_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.is_contextual
     *
     * @return the value of summary.is_contextual
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getIsContextual() {
        return isContextual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.is_contextual
     *
     * @param isContextual the value for summary.is_contextual
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setIsContextual(Byte isContextual) {
        this.isContextual = isContextual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.case_num
     *
     * @return the value of summary.case_num
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.case_num
     *
     * @param caseNum the value for summary.case_num
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCaseNum(Integer caseNum) {
        this.caseNum = caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary.case_passed
     *
     * @return the value of summary.case_passed
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCasePassed() {
        return casePassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary.case_passed
     *
     * @param casePassed the value for summary.case_passed
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCasePassed(Integer casePassed) {
        this.casePassed = casePassed;
    }
}