package com.netease.Mutest.dao;

import com.netease.Mutest.model.CaseEntity;

public interface CaseEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insert(CaseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insertSelective(CaseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    CaseEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKeySelective(CaseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKey(CaseEntity record);
}