package com.netease.Mutest.dao;

import com.netease.Mutest.model.EntityTest;

import java.util.ArrayList;

public interface EntityTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insert(EntityTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insertSelective(EntityTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    EntityTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKeySelective(EntityTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKey(EntityTest record);

    ArrayList<EntityTest> selectBySummaryId(Integer summaryId);
}