package com.netease.Mutest.dao;

import com.netease.Mutest.model.ErrorSummary;

public interface ErrorSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insert(ErrorSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insertSelective(ErrorSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    ErrorSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKeySelective(ErrorSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKey(ErrorSummary record);
}