package com.netease.Mutest.dao;

import com.netease.Mutest.model.Intent;

public interface IntentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insert(Intent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insertSelective(Intent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    Intent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKeySelective(Intent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKey(Intent record);
}