package com.netease.Mutest.dao;

import com.netease.Mutest.model.Summary;

import java.util.List;

public interface SummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insert(Summary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insertSelective(Summary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    Summary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKeySelective(Summary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKey(Summary record);

    List<Summary> selectByReportId(String reportId);
}