package com.netease.Mutest.dao;

import com.netease.Mutest.model.Intent;
import com.netease.Mutest.model.IntentTest;

import java.util.ArrayList;

public interface IntentTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insert(IntentTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int insertSelective(IntentTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    IntentTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKeySelective(IntentTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intent_test
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    int updateByPrimaryKey(IntentTest record);

    ArrayList<IntentTest> selectBySummaryId(int summaryId);
}