package com.netease.Mutest.model;

import java.util.Date;

public class CaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_entity.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_entity.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_entity.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_entity.case_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_entity.entity_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer entityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_entity.id
     *
     * @return the value of case_entity.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_entity.id
     *
     * @param id the value for case_entity.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_entity.create_time
     *
     * @return the value of case_entity.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_entity.create_time
     *
     * @param createTime the value for case_entity.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_entity.modify_time
     *
     * @return the value of case_entity.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_entity.modify_time
     *
     * @param modifyTime the value for case_entity.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_entity.case_id
     *
     * @return the value of case_entity.case_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_entity.case_id
     *
     * @param caseId the value for case_entity.case_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_entity.entity_id
     *
     * @return the value of case_entity.entity_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_entity.entity_id
     *
     * @param entityId the value for case_entity.entity_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }
}