package com.netease.Mutest.model;

import java.util.Date;

public class Cases {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.text
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.utterance
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String utterance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.has_entity
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte hasEntity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.intent_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer intentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cases.is_contextual
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte isContextual;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.id
     *
     * @return the value of cases.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.id
     *
     * @param id the value for cases.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.create_time
     *
     * @return the value of cases.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.create_time
     *
     * @param createTime the value for cases.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.modify_time
     *
     * @return the value of cases.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.modify_time
     *
     * @param modifyTime the value for cases.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.text
     *
     * @return the value of cases.text
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.text
     *
     * @param text the value for cases.text
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.utterance
     *
     * @return the value of cases.utterance
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getUtterance() {
        return utterance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.utterance
     *
     * @param utterance the value for cases.utterance
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setUtterance(String utterance) {
        this.utterance = utterance == null ? null : utterance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.has_entity
     *
     * @return the value of cases.has_entity
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getHasEntity() {
        return hasEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.has_entity
     *
     * @param hasEntity the value for cases.has_entity
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setHasEntity(Byte hasEntity) {
        this.hasEntity = hasEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.intent_id
     *
     * @return the value of cases.intent_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getIntentId() {
        return intentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.intent_id
     *
     * @param intentId the value for cases.intent_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setIntentId(Integer intentId) {
        this.intentId = intentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cases.is_contextual
     *
     * @return the value of cases.is_contextual
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getIsContextual() {
        return isContextual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cases.is_contextual
     *
     * @param isContextual the value for cases.is_contextual
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setIsContextual(Byte isContextual) {
        this.isContextual = isContextual;
    }
}