package com.netease.Mutest.model;

import java.util.Date;

public class ErrorSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_summary.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_summary.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_summary.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_summary.summary_id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer summaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_summary.case_num
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_summary.error_desc
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String errorDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_summary.id
     *
     * @return the value of error_summary.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_summary.id
     *
     * @param id the value for error_summary.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_summary.create_time
     *
     * @return the value of error_summary.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_summary.create_time
     *
     * @param createTime the value for error_summary.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_summary.modify_time
     *
     * @return the value of error_summary.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_summary.modify_time
     *
     * @param modifyTime the value for error_summary.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_summary.summary_id
     *
     * @return the value of error_summary.summary_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_summary.summary_id
     *
     * @param summaryId the value for error_summary.summary_id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setSummaryId(Integer summaryId) {
        this.summaryId = summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_summary.case_num
     *
     * @return the value of error_summary.case_num
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_summary.case_num
     *
     * @param caseNum the value for error_summary.case_num
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCaseNum(Integer caseNum) {
        this.caseNum = caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_summary.error_desc
     *
     * @return the value of error_summary.error_desc
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getErrorDesc() {
        return errorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_summary.error_desc
     *
     * @param errorDesc the value for error_summary.error_desc
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setErrorDesc(String errorDesc) {
        this.errorDesc = errorDesc == null ? null : errorDesc.trim();
    }
}