package com.netease.Mutest.model;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.create_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.modify_time
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_email
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_name
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.authority
     *
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    private Byte authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.create_time
     *
     * @return the value of users.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.create_time
     *
     * @param createTime the value for users.create_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.modify_time
     *
     * @return the value of users.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.modify_time
     *
     * @param modifyTime the value for users.modify_time
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_email
     *
     * @return the value of users.user_email
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_email
     *
     * @param userEmail the value for users.user_email
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param userName the value for users.user_name
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.authority
     *
     * @return the value of users.authority
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public Byte getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.authority
     *
     * @param authority the value for users.authority
     * @mbggenerated Fri Jun 02 09:05:42 CST 2017
     */
    public void setAuthority(Byte authority) {
        this.authority = authority;
    }
}